cache: bundler

language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

bundler_args: --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
    - INTELIPOST_API_KEY=935bd5cea9928183c53a3fcdd4d0daff4e9b18bbfdc3673fad43b2e25410a68f

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: 6ae54518b280ed0fe7aab012f10000f75e2684e62c306785a9ca54954b1faccc
